env:
  global:
  - secure: D62WmNVS4cCvqVqLskBJwC69XvfLV5EePjL0Y7IE5+S6JXUAxkHVuK05CFpN1JADhNaqyrIY+7UlmBh55Pz8fSig1Z/6zMqKeKntsKKbR43YdSW8yIZC9/cugYqyrl+OHjyzbJWV2y5LrHunZeQ/FXHS3jKoHMqGNLRxI9x0K82xJ/oC2ptsOHpNAq4CLmELr13Z1xiHcG6mXT7DOplLCC0fU1OtuIdihkM7QyTCgTxKZDL2mf72Oq1Z3I0EF9/EAae4TOx12Rfn7NCs8Gay9xeXFnatYAx8r9I1SU+CU7HXTuAl6Ew8/R6PbtyV89AsGRkUWB7DEt8A0yZLG6CA2emdXW0pvoTuFK0IKeAnfVtMLV7M+JXmj/TZrZlewTLKGYpbFFw9GFmMc4ZLlN73UlFBOO9xnnk5ypzouAzjow7guTQIlNjus5YkxjRcFyx3WiyQP4MrZfWm6xRqyMNyAw7edX8RooK/0x3kbnNgVU6x3a6MawiWoDe2mrsDbhO2E3/WsJgL78vuYmyb7C3k1U+hcVXgyDU1JfOn8fm1/NfoWVJa8dXCaTDw0ERiC1PloGrZnmGpCqOWHvHzSM4EnECnx7KJwLPtPmcnRwtQK0e5JlGGgXMqvQTa7VS9Dt98veJZqJvUDXZRZ0Tc/tWgRAwnf5akU4//ZAAvlqbP2fs=
  - secure: Fl1chympoVlXRzxkVUAG/y8W0Tt2+x+72UJ7Kdb4w1EropJZLZRH27Al7L1caPs210hwxu0LtYSHZGuanIvnB8Cj1F3TC2+UIRNBAZ5KdKml9qIYP845SpBJR6i9JesmlYoeIUv4MEnkNusV1Z255fksp9qQBPMGgpiRDHvj0RxqD/anQQyswnftxpAV6NUq4n3Cm4wJ1R2lt108WumAia5EMzH+AW2UXHfaLslaaF61r2SN0AN8TkbgmT8cNJOjeTMeK8dkGsWGDV5K+lhTDWyUCX+MXmI4H3crCZWty8EglRiSVMwphjpRpt1WjPdwED2imDyco7rQjsBpwafqzqkt02yS0QS3yG/WatIA69eVxIr5APBWieM/G/pq/0dtt8aLkhTXEpxP+lkDgv8pj2/hpPI8mD/uRTBN/jMDw3eaiJC3R05OrDN25aDSNqTlPPkhgjxLZ2h35aY9/uvT77LxvN64OjDdmw7BM2cUSC0iAA29MyOLl+3jeSj//9+IGgmvB2rn3r58gooDSL7yXeCC++T5RSp726nvtLHcJpFrlnII72nxnJrJTT/BuBirxBU3dqfkNqx87JbPRlRHhKtY5sX9iyy4IM3ozSxAIzbr7Ufb/AoImhett45hdmSSBO4hBI861yLsFFHzlQm9QeEJpBIz1wnb+PsePyz/KTI=
services:
- docker
script:
- docker build -t openhab-cloud .
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    docker login -u $DOCKER_USER -p $DOCKER_PASSWORD;
    docker tag openhab-cloud $TRAVIS_REPO_SLUG:latest;
    docker push $TRAVIS_REPO_SLUG:latest;
  fi
- if [[ -n "$TRAVIS_TAG" ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    docker login -u $DOCKER_USER -p $DOCKER_PASSWORD;
    docker tag openhab-cloud $TRAVIS_REPO_SLUG:$TRAVIS_TAG;
    docker push $TRAVIS_REPO_SLUG:$TRAVIS_TAG;
  fi
